<?php
/**
 * @file
 * This module track all pages on Omniture dynamically.
 */

/**
 * Implementation of hook_init().
 */
function omniture_init() {
  $s_account = variable_get('omniture_s_account', '');

  // do not track anything if tracking account is not set
  if (empty($s_account)) {
    return;
  }
  
  global $user;
  // Check if we should track the currently active user's role.
  $track = 0;
  if (is_array($user->roles)) {
    foreach ($user->roles as $role) {
      $role = str_replace(' ', '_', $role);
      $track += variable_get("omniture_{$role}", FALSE);
    }
  }
  
  // Don't track page views in the admin sections, or for certain roles.
  if (arg(0) != 'admin' && $track > 0 && $user->uid != 1) {
    module_load_include('inc', 'omniture', 'inc/omniture.common');
    _omniture_include_current_page_js();
  }
}

/**
 * Implements hook_help().
 */
function omniture_help($path, $arg) {
  switch ($path) {
    case 'admin/help#omniture':
      return t('Settings for Omniture module');
  }
}

/**
 * Implements hook_permission().
 */
function omniture_permission() {
  return array(
    'administer omniture configuration' => array(
      'title' => t('Omniture configuration'),
    )
  );
}

/**
 * Implementation of hook_menu().
 */
function omniture_menu() {
  $items = array();
  
  $items['admin/config/omniture'] = array(
    'title' => 'Omniture',
    'description' => 'Adjust omniture options.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('omniture_url_admin_settings'),
    'access arguments' => array('administer omniture configuration'),
    'file' => 'inc/omniture.admin.inc',
  );
  
  $items['admin/config/omniture/url_settings'] = array(
    'title' => 'Omniture Url settings',
    'description' => 'Adjust omniture url settings.',
    'weight' => -5,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  $items['admin/config/omniture/content_type_settings'] = array(
    'title' => 'Omniture Content Type settings',
    'description' => 'Adjust omniture content type settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('omniture_content_type_admin_settings'),
    'access arguments' => array('administer omniture configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/omniture.admin.inc',
    'weight' => 5,
  );
  
  return $items;
}